WSC CI:
  script:
  - git ls-files | xargs wc -l
  - find . -type f -name '*.php' -not -path "./WCF/*" |xargs -I file php -l file
  - git clone --branch=next --depth=1 --quiet git://github.com/WoltLab/WCF.git WCF
  - phpcs -p --extensions=php --standard="`pwd`/WCF/CodeSniff/WCF" . --ignore="/WCF/*" --ignore="/files/lib/system/api/phpqrcode/*"
